/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"


#import "Core.h"

@implementation ServiceException_t

- (id) init
{
  return [super initWithName: @"ServiceException_t" reason: @"unknown" userInfo: nil];
}

- (id) initWithErrorCode: (int32_t) errorCode errorDesc: (NSString *) errorDesc
{
  self = [self init];
  __errorCode = errorCode;
  __errorCode_isset = YES;
  __errorDesc = [errorDesc retain_stub];
  __errorDesc_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super initWithCoder: decoder];
  if ([decoder containsValueForKey: @"errorCode"])
  {
    __errorCode = [decoder decodeInt32ForKey: @"errorCode"];
    __errorCode_isset = YES;
  }
  if ([decoder containsValueForKey: @"errorDesc"])
  {
    __errorDesc = [[decoder decodeObjectForKey: @"errorDesc"] retain_stub];
    __errorDesc_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  [super encodeWithCoder: encoder];
  if (__errorCode_isset)
  {
    [encoder encodeInt32: __errorCode forKey: @"errorCode"];
  }
  if (__errorDesc_isset)
  {
    [encoder encodeObject: __errorDesc forKey: @"errorDesc"];
  }
}

- (void) dealloc
{
  [__errorDesc release_stub];
  [super dealloc_stub];
}

- (int32_t) errorCode {
  return __errorCode;
}

- (void) setErrorCode: (int32_t) errorCode {
  __errorCode = errorCode;
  __errorCode_isset = YES;
}

- (BOOL) errorCodeIsSet {
  return __errorCode_isset;
}

- (void) unsetErrorCode {
  __errorCode_isset = NO;
}

- (NSString *) errorDesc {
  return [[__errorDesc retain_stub] autorelease_stub];
}

- (void) setErrorDesc: (NSString *) errorDesc {
  [errorDesc retain_stub];
  [__errorDesc release_stub];
  __errorDesc = errorDesc;
  __errorDesc_isset = YES;
}

- (BOOL) errorDescIsSet {
  return __errorDesc_isset;
}

- (void) unsetErrorDesc {
  [__errorDesc release_stub];
  __errorDesc = nil;
  __errorDesc_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setErrorCode: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setErrorDesc: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ServiceException_t"];
  if (__errorCode_isset) {
    [outProtocol writeFieldBeginWithName: @"errorCode" type: TType_I32 fieldID: 1];
    [outProtocol writeI32: __errorCode];
    [outProtocol writeFieldEnd];
  }
  if (__errorDesc_isset) {
    if (__errorDesc != nil) {
      [outProtocol writeFieldBeginWithName: @"errorDesc" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __errorDesc];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ServiceException_t("];
  [ms appendString: @"errorCode:"];
  [ms appendFormat: @"%i", __errorCode];
  [ms appendString: @",errorDesc:"];
  [ms appendFormat: @"\"%@\"", __errorDesc];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation SocialNetworkDetail_t

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSocalNetwork: (int) socalNetwork name: (NSString *) name website: (NSString *) website apiUrl: (NSString *) apiUrl
{
  self = [super init];
  __socalNetwork = socalNetwork;
  __socalNetwork_isset = YES;
  __name = [name retain_stub];
  __name_isset = YES;
  __website = [website retain_stub];
  __website_isset = YES;
  __apiUrl = [apiUrl retain_stub];
  __apiUrl_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"socalNetwork"])
  {
    __socalNetwork = [decoder decodeIntForKey: @"socalNetwork"];
    __socalNetwork_isset = YES;
  }
  if ([decoder containsValueForKey: @"name"])
  {
    __name = [[decoder decodeObjectForKey: @"name"] retain_stub];
    __name_isset = YES;
  }
  if ([decoder containsValueForKey: @"website"])
  {
    __website = [[decoder decodeObjectForKey: @"website"] retain_stub];
    __website_isset = YES;
  }
  if ([decoder containsValueForKey: @"apiUrl"])
  {
    __apiUrl = [[decoder decodeObjectForKey: @"apiUrl"] retain_stub];
    __apiUrl_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__socalNetwork_isset)
  {
    [encoder encodeInt: __socalNetwork forKey: @"socalNetwork"];
  }
  if (__name_isset)
  {
    [encoder encodeObject: __name forKey: @"name"];
  }
  if (__website_isset)
  {
    [encoder encodeObject: __website forKey: @"website"];
  }
  if (__apiUrl_isset)
  {
    [encoder encodeObject: __apiUrl forKey: @"apiUrl"];
  }
}

- (void) dealloc
{
  [__name release_stub];
  [__website release_stub];
  [__apiUrl release_stub];
  [super dealloc_stub];
}

- (int) socalNetwork {
  return __socalNetwork;
}

- (void) setSocalNetwork: (int) socalNetwork {
  __socalNetwork = socalNetwork;
  __socalNetwork_isset = YES;
}

- (BOOL) socalNetworkIsSet {
  return __socalNetwork_isset;
}

- (void) unsetSocalNetwork {
  __socalNetwork_isset = NO;
}

- (NSString *) name {
  return [[__name retain_stub] autorelease_stub];
}

- (void) setName: (NSString *) name {
  [name retain_stub];
  [__name release_stub];
  __name = name;
  __name_isset = YES;
}

- (BOOL) nameIsSet {
  return __name_isset;
}

- (void) unsetName {
  [__name release_stub];
  __name = nil;
  __name_isset = NO;
}

- (NSString *) website {
  return [[__website retain_stub] autorelease_stub];
}

- (void) setWebsite: (NSString *) website {
  [website retain_stub];
  [__website release_stub];
  __website = website;
  __website_isset = YES;
}

- (BOOL) websiteIsSet {
  return __website_isset;
}

- (void) unsetWebsite {
  [__website release_stub];
  __website = nil;
  __website_isset = NO;
}

- (NSString *) apiUrl {
  return [[__apiUrl retain_stub] autorelease_stub];
}

- (void) setApiUrl: (NSString *) apiUrl {
  [apiUrl retain_stub];
  [__apiUrl release_stub];
  __apiUrl = apiUrl;
  __apiUrl_isset = YES;
}

- (BOOL) apiUrlIsSet {
  return __apiUrl_isset;
}

- (void) unsetApiUrl {
  [__apiUrl release_stub];
  __apiUrl = nil;
  __apiUrl_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I32) {
          int fieldValue = [inProtocol readI32];
          [self setSocalNetwork: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setWebsite: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setApiUrl: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"SocialNetworkDetail_t"];
  if (__socalNetwork_isset) {
    [outProtocol writeFieldBeginWithName: @"socalNetwork" type: TType_I32 fieldID: 1];
    [outProtocol writeI32: __socalNetwork];
    [outProtocol writeFieldEnd];
  }
  if (__name_isset) {
    if (__name != nil) {
      [outProtocol writeFieldBeginWithName: @"name" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __name];
      [outProtocol writeFieldEnd];
    }
  }
  if (__website_isset) {
    if (__website != nil) {
      [outProtocol writeFieldBeginWithName: @"website" type: TType_STRING fieldID: 3];
      [outProtocol writeString: __website];
      [outProtocol writeFieldEnd];
    }
  }
  if (__apiUrl_isset) {
    if (__apiUrl != nil) {
      [outProtocol writeFieldBeginWithName: @"apiUrl" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __apiUrl];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"SocialNetworkDetail_t("];
  [ms appendString: @"socalNetwork:"];
  [ms appendFormat: @"%i", __socalNetwork];
  [ms appendString: @",name:"];
  [ms appendFormat: @"\"%@\"", __name];
  [ms appendString: @",website:"];
  [ms appendFormat: @"\"%@\"", __website];
  [ms appendString: @",apiUrl:"];
  [ms appendFormat: @"\"%@\"", __apiUrl];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation SocialAccount_t

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSocalNetwork: (int) socalNetwork loginId: (NSString *) loginId token: (NSString *) token created: (Timestamp) created updated: (Timestamp) updated
{
  self = [super init];
  __socalNetwork = socalNetwork;
  __socalNetwork_isset = YES;
  __loginId = [loginId retain_stub];
  __loginId_isset = YES;
  __token = [token retain_stub];
  __token_isset = YES;
  __created = created;
  __created_isset = YES;
  __updated = updated;
  __updated_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"socalNetwork"])
  {
    __socalNetwork = [decoder decodeIntForKey: @"socalNetwork"];
    __socalNetwork_isset = YES;
  }
  if ([decoder containsValueForKey: @"loginId"])
  {
    __loginId = [[decoder decodeObjectForKey: @"loginId"] retain_stub];
    __loginId_isset = YES;
  }
  if ([decoder containsValueForKey: @"token"])
  {
    __token = [[decoder decodeObjectForKey: @"token"] retain_stub];
    __token_isset = YES;
  }
  if ([decoder containsValueForKey: @"created"])
  {
    __created = [decoder decodeInt64ForKey: @"created"];
    __created_isset = YES;
  }
  if ([decoder containsValueForKey: @"updated"])
  {
    __updated = [decoder decodeInt64ForKey: @"updated"];
    __updated_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__socalNetwork_isset)
  {
    [encoder encodeInt: __socalNetwork forKey: @"socalNetwork"];
  }
  if (__loginId_isset)
  {
    [encoder encodeObject: __loginId forKey: @"loginId"];
  }
  if (__token_isset)
  {
    [encoder encodeObject: __token forKey: @"token"];
  }
  if (__created_isset)
  {
    [encoder encodeInt64: __created forKey: @"created"];
  }
  if (__updated_isset)
  {
    [encoder encodeInt64: __updated forKey: @"updated"];
  }
}

- (void) dealloc
{
  [__loginId release_stub];
  [__token release_stub];
  [super dealloc_stub];
}

- (int) socalNetwork {
  return __socalNetwork;
}

- (void) setSocalNetwork: (int) socalNetwork {
  __socalNetwork = socalNetwork;
  __socalNetwork_isset = YES;
}

- (BOOL) socalNetworkIsSet {
  return __socalNetwork_isset;
}

- (void) unsetSocalNetwork {
  __socalNetwork_isset = NO;
}

- (NSString *) loginId {
  return [[__loginId retain_stub] autorelease_stub];
}

- (void) setLoginId: (NSString *) loginId {
  [loginId retain_stub];
  [__loginId release_stub];
  __loginId = loginId;
  __loginId_isset = YES;
}

- (BOOL) loginIdIsSet {
  return __loginId_isset;
}

- (void) unsetLoginId {
  [__loginId release_stub];
  __loginId = nil;
  __loginId_isset = NO;
}

- (NSString *) token {
  return [[__token retain_stub] autorelease_stub];
}

- (void) setToken: (NSString *) token {
  [token retain_stub];
  [__token release_stub];
  __token = token;
  __token_isset = YES;
}

- (BOOL) tokenIsSet {
  return __token_isset;
}

- (void) unsetToken {
  [__token release_stub];
  __token = nil;
  __token_isset = NO;
}

- (int64_t) created {
  return __created;
}

- (void) setCreated: (int64_t) created {
  __created = created;
  __created_isset = YES;
}

- (BOOL) createdIsSet {
  return __created_isset;
}

- (void) unsetCreated {
  __created_isset = NO;
}

- (int64_t) updated {
  return __updated;
}

- (void) setUpdated: (int64_t) updated {
  __updated = updated;
  __updated_isset = YES;
}

- (BOOL) updatedIsSet {
  return __updated_isset;
}

- (void) unsetUpdated {
  __updated_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I32) {
          int fieldValue = [inProtocol readI32];
          [self setSocalNetwork: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setLoginId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setToken: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 20:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setCreated: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 21:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setUpdated: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"SocialAccount_t"];
  if (__socalNetwork_isset) {
    [outProtocol writeFieldBeginWithName: @"socalNetwork" type: TType_I32 fieldID: 1];
    [outProtocol writeI32: __socalNetwork];
    [outProtocol writeFieldEnd];
  }
  if (__loginId_isset) {
    if (__loginId != nil) {
      [outProtocol writeFieldBeginWithName: @"loginId" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __loginId];
      [outProtocol writeFieldEnd];
    }
  }
  if (__token_isset) {
    if (__token != nil) {
      [outProtocol writeFieldBeginWithName: @"token" type: TType_STRING fieldID: 3];
      [outProtocol writeString: __token];
      [outProtocol writeFieldEnd];
    }
  }
  if (__created_isset) {
    [outProtocol writeFieldBeginWithName: @"created" type: TType_I64 fieldID: 20];
    [outProtocol writeI64: __created];
    [outProtocol writeFieldEnd];
  }
  if (__updated_isset) {
    [outProtocol writeFieldBeginWithName: @"updated" type: TType_I64 fieldID: 21];
    [outProtocol writeI64: __updated];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"SocialAccount_t("];
  [ms appendString: @"socalNetwork:"];
  [ms appendFormat: @"%i", __socalNetwork];
  [ms appendString: @",loginId:"];
  [ms appendFormat: @"\"%@\"", __loginId];
  [ms appendString: @",token:"];
  [ms appendFormat: @"\"%@\"", __token];
  [ms appendString: @",created:"];
  [ms appendFormat: @"%qi", __created];
  [ms appendString: @",updated:"];
  [ms appendFormat: @"%qi", __updated];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation Address_t

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithAddressId: (int64_t) addressId address1: (NSString *) address1 address2: (NSString *) address2 city: (NSString *) city stateProvinceCounty: (NSString *) stateProvinceCounty zip: (NSString *) zip country: (NSString *) country
{
  self = [super init];
  __addressId = addressId;
  __addressId_isset = YES;
  __address1 = [address1 retain_stub];
  __address1_isset = YES;
  __address2 = [address2 retain_stub];
  __address2_isset = YES;
  __city = [city retain_stub];
  __city_isset = YES;
  __stateProvinceCounty = [stateProvinceCounty retain_stub];
  __stateProvinceCounty_isset = YES;
  __zip = [zip retain_stub];
  __zip_isset = YES;
  __country = [country retain_stub];
  __country_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"addressId"])
  {
    __addressId = [decoder decodeInt64ForKey: @"addressId"];
    __addressId_isset = YES;
  }
  if ([decoder containsValueForKey: @"address1"])
  {
    __address1 = [[decoder decodeObjectForKey: @"address1"] retain_stub];
    __address1_isset = YES;
  }
  if ([decoder containsValueForKey: @"address2"])
  {
    __address2 = [[decoder decodeObjectForKey: @"address2"] retain_stub];
    __address2_isset = YES;
  }
  if ([decoder containsValueForKey: @"city"])
  {
    __city = [[decoder decodeObjectForKey: @"city"] retain_stub];
    __city_isset = YES;
  }
  if ([decoder containsValueForKey: @"stateProvinceCounty"])
  {
    __stateProvinceCounty = [[decoder decodeObjectForKey: @"stateProvinceCounty"] retain_stub];
    __stateProvinceCounty_isset = YES;
  }
  if ([decoder containsValueForKey: @"zip"])
  {
    __zip = [[decoder decodeObjectForKey: @"zip"] retain_stub];
    __zip_isset = YES;
  }
  if ([decoder containsValueForKey: @"country"])
  {
    __country = [[decoder decodeObjectForKey: @"country"] retain_stub];
    __country_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__addressId_isset)
  {
    [encoder encodeInt64: __addressId forKey: @"addressId"];
  }
  if (__address1_isset)
  {
    [encoder encodeObject: __address1 forKey: @"address1"];
  }
  if (__address2_isset)
  {
    [encoder encodeObject: __address2 forKey: @"address2"];
  }
  if (__city_isset)
  {
    [encoder encodeObject: __city forKey: @"city"];
  }
  if (__stateProvinceCounty_isset)
  {
    [encoder encodeObject: __stateProvinceCounty forKey: @"stateProvinceCounty"];
  }
  if (__zip_isset)
  {
    [encoder encodeObject: __zip forKey: @"zip"];
  }
  if (__country_isset)
  {
    [encoder encodeObject: __country forKey: @"country"];
  }
}

- (void) dealloc
{
  [__address1 release_stub];
  [__address2 release_stub];
  [__city release_stub];
  [__stateProvinceCounty release_stub];
  [__zip release_stub];
  [__country release_stub];
  [super dealloc_stub];
}

- (int64_t) addressId {
  return __addressId;
}

- (void) setAddressId: (int64_t) addressId {
  __addressId = addressId;
  __addressId_isset = YES;
}

- (BOOL) addressIdIsSet {
  return __addressId_isset;
}

- (void) unsetAddressId {
  __addressId_isset = NO;
}

- (NSString *) address1 {
  return [[__address1 retain_stub] autorelease_stub];
}

- (void) setAddress1: (NSString *) address1 {
  [address1 retain_stub];
  [__address1 release_stub];
  __address1 = address1;
  __address1_isset = YES;
}

- (BOOL) address1IsSet {
  return __address1_isset;
}

- (void) unsetAddress1 {
  [__address1 release_stub];
  __address1 = nil;
  __address1_isset = NO;
}

- (NSString *) address2 {
  return [[__address2 retain_stub] autorelease_stub];
}

- (void) setAddress2: (NSString *) address2 {
  [address2 retain_stub];
  [__address2 release_stub];
  __address2 = address2;
  __address2_isset = YES;
}

- (BOOL) address2IsSet {
  return __address2_isset;
}

- (void) unsetAddress2 {
  [__address2 release_stub];
  __address2 = nil;
  __address2_isset = NO;
}

- (NSString *) city {
  return [[__city retain_stub] autorelease_stub];
}

- (void) setCity: (NSString *) city {
  [city retain_stub];
  [__city release_stub];
  __city = city;
  __city_isset = YES;
}

- (BOOL) cityIsSet {
  return __city_isset;
}

- (void) unsetCity {
  [__city release_stub];
  __city = nil;
  __city_isset = NO;
}

- (NSString *) stateProvinceCounty {
  return [[__stateProvinceCounty retain_stub] autorelease_stub];
}

- (void) setStateProvinceCounty: (NSString *) stateProvinceCounty {
  [stateProvinceCounty retain_stub];
  [__stateProvinceCounty release_stub];
  __stateProvinceCounty = stateProvinceCounty;
  __stateProvinceCounty_isset = YES;
}

- (BOOL) stateProvinceCountyIsSet {
  return __stateProvinceCounty_isset;
}

- (void) unsetStateProvinceCounty {
  [__stateProvinceCounty release_stub];
  __stateProvinceCounty = nil;
  __stateProvinceCounty_isset = NO;
}

- (NSString *) zip {
  return [[__zip retain_stub] autorelease_stub];
}

- (void) setZip: (NSString *) zip {
  [zip retain_stub];
  [__zip release_stub];
  __zip = zip;
  __zip_isset = YES;
}

- (BOOL) zipIsSet {
  return __zip_isset;
}

- (void) unsetZip {
  [__zip release_stub];
  __zip = nil;
  __zip_isset = NO;
}

- (NSString *) country {
  return [[__country retain_stub] autorelease_stub];
}

- (void) setCountry: (NSString *) country {
  [country retain_stub];
  [__country release_stub];
  __country = country;
  __country_isset = YES;
}

- (BOOL) countryIsSet {
  return __country_isset;
}

- (void) unsetCountry {
  [__country release_stub];
  __country = nil;
  __country_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setAddressId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setAddress1: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setAddress2: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setCity: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 5:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setStateProvinceCounty: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 6:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setZip: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 7:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setCountry: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Address_t"];
  if (__addressId_isset) {
    [outProtocol writeFieldBeginWithName: @"addressId" type: TType_I64 fieldID: 1];
    [outProtocol writeI64: __addressId];
    [outProtocol writeFieldEnd];
  }
  if (__address1_isset) {
    if (__address1 != nil) {
      [outProtocol writeFieldBeginWithName: @"address1" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __address1];
      [outProtocol writeFieldEnd];
    }
  }
  if (__address2_isset) {
    if (__address2 != nil) {
      [outProtocol writeFieldBeginWithName: @"address2" type: TType_STRING fieldID: 3];
      [outProtocol writeString: __address2];
      [outProtocol writeFieldEnd];
    }
  }
  if (__city_isset) {
    if (__city != nil) {
      [outProtocol writeFieldBeginWithName: @"city" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __city];
      [outProtocol writeFieldEnd];
    }
  }
  if (__stateProvinceCounty_isset) {
    if (__stateProvinceCounty != nil) {
      [outProtocol writeFieldBeginWithName: @"stateProvinceCounty" type: TType_STRING fieldID: 5];
      [outProtocol writeString: __stateProvinceCounty];
      [outProtocol writeFieldEnd];
    }
  }
  if (__zip_isset) {
    if (__zip != nil) {
      [outProtocol writeFieldBeginWithName: @"zip" type: TType_STRING fieldID: 6];
      [outProtocol writeString: __zip];
      [outProtocol writeFieldEnd];
    }
  }
  if (__country_isset) {
    if (__country != nil) {
      [outProtocol writeFieldBeginWithName: @"country" type: TType_STRING fieldID: 7];
      [outProtocol writeString: __country];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Address_t("];
  [ms appendString: @"addressId:"];
  [ms appendFormat: @"%qi", __addressId];
  [ms appendString: @",address1:"];
  [ms appendFormat: @"\"%@\"", __address1];
  [ms appendString: @",address2:"];
  [ms appendFormat: @"\"%@\"", __address2];
  [ms appendString: @",city:"];
  [ms appendFormat: @"\"%@\"", __city];
  [ms appendString: @",stateProvinceCounty:"];
  [ms appendFormat: @"\"%@\"", __stateProvinceCounty];
  [ms appendString: @",zip:"];
  [ms appendFormat: @"\"%@\"", __zip];
  [ms appendString: @",country:"];
  [ms appendFormat: @"\"%@\"", __country];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation Customer_t

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithCustomerId: (int64_t) customerId firstName: (NSString *) firstName lastName: (NSString *) lastName email: (NSString *) email sex: (int) sex socialAccounts: (NSMutableDictionary *) socialAccounts created: (Timestamp) created updated: (Timestamp) updated
{
  self = [super init];
  __customerId = customerId;
  __customerId_isset = YES;
  __firstName = [firstName retain_stub];
  __firstName_isset = YES;
  __lastName = [lastName retain_stub];
  __lastName_isset = YES;
  __email = [email retain_stub];
  __email_isset = YES;
  __sex = sex;
  __sex_isset = YES;
  __socialAccounts = [socialAccounts retain_stub];
  __socialAccounts_isset = YES;
  __created = created;
  __created_isset = YES;
  __updated = updated;
  __updated_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"customerId"])
  {
    __customerId = [decoder decodeInt64ForKey: @"customerId"];
    __customerId_isset = YES;
  }
  if ([decoder containsValueForKey: @"firstName"])
  {
    __firstName = [[decoder decodeObjectForKey: @"firstName"] retain_stub];
    __firstName_isset = YES;
  }
  if ([decoder containsValueForKey: @"lastName"])
  {
    __lastName = [[decoder decodeObjectForKey: @"lastName"] retain_stub];
    __lastName_isset = YES;
  }
  if ([decoder containsValueForKey: @"email"])
  {
    __email = [[decoder decodeObjectForKey: @"email"] retain_stub];
    __email_isset = YES;
  }
  if ([decoder containsValueForKey: @"sex"])
  {
    __sex = [decoder decodeIntForKey: @"sex"];
    __sex_isset = YES;
  }
  if ([decoder containsValueForKey: @"socialAccounts"])
  {
    __socialAccounts = [[decoder decodeObjectForKey: @"socialAccounts"] retain_stub];
    __socialAccounts_isset = YES;
  }
  if ([decoder containsValueForKey: @"created"])
  {
    __created = [decoder decodeInt64ForKey: @"created"];
    __created_isset = YES;
  }
  if ([decoder containsValueForKey: @"updated"])
  {
    __updated = [decoder decodeInt64ForKey: @"updated"];
    __updated_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__customerId_isset)
  {
    [encoder encodeInt64: __customerId forKey: @"customerId"];
  }
  if (__firstName_isset)
  {
    [encoder encodeObject: __firstName forKey: @"firstName"];
  }
  if (__lastName_isset)
  {
    [encoder encodeObject: __lastName forKey: @"lastName"];
  }
  if (__email_isset)
  {
    [encoder encodeObject: __email forKey: @"email"];
  }
  if (__sex_isset)
  {
    [encoder encodeInt: __sex forKey: @"sex"];
  }
  if (__socialAccounts_isset)
  {
    [encoder encodeObject: __socialAccounts forKey: @"socialAccounts"];
  }
  if (__created_isset)
  {
    [encoder encodeInt64: __created forKey: @"created"];
  }
  if (__updated_isset)
  {
    [encoder encodeInt64: __updated forKey: @"updated"];
  }
}

- (void) dealloc
{
  [__firstName release_stub];
  [__lastName release_stub];
  [__email release_stub];
  [__socialAccounts release_stub];
  [super dealloc_stub];
}

- (int64_t) customerId {
  return __customerId;
}

- (void) setCustomerId: (int64_t) customerId {
  __customerId = customerId;
  __customerId_isset = YES;
}

- (BOOL) customerIdIsSet {
  return __customerId_isset;
}

- (void) unsetCustomerId {
  __customerId_isset = NO;
}

- (NSString *) firstName {
  return [[__firstName retain_stub] autorelease_stub];
}

- (void) setFirstName: (NSString *) firstName {
  [firstName retain_stub];
  [__firstName release_stub];
  __firstName = firstName;
  __firstName_isset = YES;
}

- (BOOL) firstNameIsSet {
  return __firstName_isset;
}

- (void) unsetFirstName {
  [__firstName release_stub];
  __firstName = nil;
  __firstName_isset = NO;
}

- (NSString *) lastName {
  return [[__lastName retain_stub] autorelease_stub];
}

- (void) setLastName: (NSString *) lastName {
  [lastName retain_stub];
  [__lastName release_stub];
  __lastName = lastName;
  __lastName_isset = YES;
}

- (BOOL) lastNameIsSet {
  return __lastName_isset;
}

- (void) unsetLastName {
  [__lastName release_stub];
  __lastName = nil;
  __lastName_isset = NO;
}

- (NSString *) email {
  return [[__email retain_stub] autorelease_stub];
}

- (void) setEmail: (NSString *) email {
  [email retain_stub];
  [__email release_stub];
  __email = email;
  __email_isset = YES;
}

- (BOOL) emailIsSet {
  return __email_isset;
}

- (void) unsetEmail {
  [__email release_stub];
  __email = nil;
  __email_isset = NO;
}

- (int) sex {
  return __sex;
}

- (void) setSex: (int) sex {
  __sex = sex;
  __sex_isset = YES;
}

- (BOOL) sexIsSet {
  return __sex_isset;
}

- (void) unsetSex {
  __sex_isset = NO;
}

- (NSMutableDictionary *) socialAccounts {
  return [[__socialAccounts retain_stub] autorelease_stub];
}

- (void) setSocialAccounts: (NSMutableDictionary *) socialAccounts {
  [socialAccounts retain_stub];
  [__socialAccounts release_stub];
  __socialAccounts = socialAccounts;
  __socialAccounts_isset = YES;
}

- (BOOL) socialAccountsIsSet {
  return __socialAccounts_isset;
}

- (void) unsetSocialAccounts {
  [__socialAccounts release_stub];
  __socialAccounts = nil;
  __socialAccounts_isset = NO;
}

- (int64_t) created {
  return __created;
}

- (void) setCreated: (int64_t) created {
  __created = created;
  __created_isset = YES;
}

- (BOOL) createdIsSet {
  return __created_isset;
}

- (void) unsetCreated {
  __created_isset = NO;
}

- (int64_t) updated {
  return __updated;
}

- (void) setUpdated: (int64_t) updated {
  __updated = updated;
  __updated_isset = YES;
}

- (BOOL) updatedIsSet {
  return __updated_isset;
}

- (void) unsetUpdated {
  __updated_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setCustomerId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setFirstName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setLastName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setEmail: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 6:
        if (fieldType == TType_I32) {
          int fieldValue = [inProtocol readI32];
          [self setSex: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 7:
        if (fieldType == TType_MAP) {
          int _size0;
          [inProtocol readMapBeginReturningKeyType: NULL valueType: NULL size: &_size0];
          NSMutableDictionary * fieldValue = [[NSMutableDictionary alloc] initWithCapacity: _size0];
          int _i1;
          for (_i1 = 0; _i1 < _size0; ++_i1)
          {
            int _key2 = [inProtocol readI32];
            SocialAccount_t *_val3 = [[SocialAccount_t alloc] init];
            [_val3 read: inProtocol];
            [fieldValue setObject: _val3 forKey: [NSNumber numberWithInt: _key2]];
            [_val3 release_stub];
          }
          [inProtocol readMapEnd];
          [self setSocialAccounts: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 20:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setCreated: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 21:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setUpdated: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Customer_t"];
  if (__customerId_isset) {
    [outProtocol writeFieldBeginWithName: @"customerId" type: TType_I64 fieldID: 1];
    [outProtocol writeI64: __customerId];
    [outProtocol writeFieldEnd];
  }
  if (__firstName_isset) {
    if (__firstName != nil) {
      [outProtocol writeFieldBeginWithName: @"firstName" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __firstName];
      [outProtocol writeFieldEnd];
    }
  }
  if (__lastName_isset) {
    if (__lastName != nil) {
      [outProtocol writeFieldBeginWithName: @"lastName" type: TType_STRING fieldID: 3];
      [outProtocol writeString: __lastName];
      [outProtocol writeFieldEnd];
    }
  }
  if (__email_isset) {
    if (__email != nil) {
      [outProtocol writeFieldBeginWithName: @"email" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __email];
      [outProtocol writeFieldEnd];
    }
  }
  if (__sex_isset) {
    [outProtocol writeFieldBeginWithName: @"sex" type: TType_I32 fieldID: 6];
    [outProtocol writeI32: __sex];
    [outProtocol writeFieldEnd];
  }
  if (__socialAccounts_isset) {
    if (__socialAccounts != nil) {
      [outProtocol writeFieldBeginWithName: @"socialAccounts" type: TType_MAP fieldID: 7];
      {
        [outProtocol writeMapBeginWithKeyType: TType_I32 valueType: TType_STRUCT size: [__socialAccounts count]];
        NSEnumerator * _iter4 = [__socialAccounts keyEnumerator];
        id key5;
        while ((key5 = [_iter4 nextObject]))
        {
          [outProtocol writeI32: [key5 intValue]];
          [[__socialAccounts objectForKey: key5] write: outProtocol];
        }
        [outProtocol writeMapEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  if (__created_isset) {
    [outProtocol writeFieldBeginWithName: @"created" type: TType_I64 fieldID: 20];
    [outProtocol writeI64: __created];
    [outProtocol writeFieldEnd];
  }
  if (__updated_isset) {
    [outProtocol writeFieldBeginWithName: @"updated" type: TType_I64 fieldID: 21];
    [outProtocol writeI64: __updated];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Customer_t("];
  [ms appendString: @"customerId:"];
  [ms appendFormat: @"%qi", __customerId];
  [ms appendString: @",firstName:"];
  [ms appendFormat: @"\"%@\"", __firstName];
  [ms appendString: @",lastName:"];
  [ms appendFormat: @"\"%@\"", __lastName];
  [ms appendString: @",email:"];
  [ms appendFormat: @"\"%@\"", __email];
  [ms appendString: @",sex:"];
  [ms appendFormat: @"%i", __sex];
  [ms appendString: @",socialAccounts:"];
  [ms appendFormat: @"%@", __socialAccounts];
  [ms appendString: @",created:"];
  [ms appendFormat: @"%qi", __created];
  [ms appendString: @",updated:"];
  [ms appendFormat: @"%qi", __updated];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation Token_t

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithAccountId: (NSString *) accountId email: (NSString *) email expires: (int64_t) expires
{
  self = [super init];
  __accountId = [accountId retain_stub];
  __accountId_isset = YES;
  __email = [email retain_stub];
  __email_isset = YES;
  __expires = expires;
  __expires_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"accountId"])
  {
    __accountId = [[decoder decodeObjectForKey: @"accountId"] retain_stub];
    __accountId_isset = YES;
  }
  if ([decoder containsValueForKey: @"email"])
  {
    __email = [[decoder decodeObjectForKey: @"email"] retain_stub];
    __email_isset = YES;
  }
  if ([decoder containsValueForKey: @"expires"])
  {
    __expires = [decoder decodeInt64ForKey: @"expires"];
    __expires_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__accountId_isset)
  {
    [encoder encodeObject: __accountId forKey: @"accountId"];
  }
  if (__email_isset)
  {
    [encoder encodeObject: __email forKey: @"email"];
  }
  if (__expires_isset)
  {
    [encoder encodeInt64: __expires forKey: @"expires"];
  }
}

- (void) dealloc
{
  [__accountId release_stub];
  [__email release_stub];
  [super dealloc_stub];
}

- (NSString *) accountId {
  return [[__accountId retain_stub] autorelease_stub];
}

- (void) setAccountId: (NSString *) accountId {
  [accountId retain_stub];
  [__accountId release_stub];
  __accountId = accountId;
  __accountId_isset = YES;
}

- (BOOL) accountIdIsSet {
  return __accountId_isset;
}

- (void) unsetAccountId {
  [__accountId release_stub];
  __accountId = nil;
  __accountId_isset = NO;
}

- (NSString *) email {
  return [[__email retain_stub] autorelease_stub];
}

- (void) setEmail: (NSString *) email {
  [email retain_stub];
  [__email release_stub];
  __email = email;
  __email_isset = YES;
}

- (BOOL) emailIsSet {
  return __email_isset;
}

- (void) unsetEmail {
  [__email release_stub];
  __email = nil;
  __email_isset = NO;
}

- (int64_t) expires {
  return __expires;
}

- (void) setExpires: (int64_t) expires {
  __expires = expires;
  __expires_isset = YES;
}

- (BOOL) expiresIsSet {
  return __expires_isset;
}

- (void) unsetExpires {
  __expires_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setAccountId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setEmail: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setExpires: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Token_t"];
  if (__accountId_isset) {
    if (__accountId != nil) {
      [outProtocol writeFieldBeginWithName: @"accountId" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __accountId];
      [outProtocol writeFieldEnd];
    }
  }
  if (__email_isset) {
    if (__email != nil) {
      [outProtocol writeFieldBeginWithName: @"email" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __email];
      [outProtocol writeFieldEnd];
    }
  }
  if (__expires_isset) {
    [outProtocol writeFieldBeginWithName: @"expires" type: TType_I64 fieldID: 3];
    [outProtocol writeI64: __expires];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Token_t("];
  [ms appendString: @"accountId:"];
  [ms appendFormat: @"\"%@\"", __accountId];
  [ms appendString: @",email:"];
  [ms appendFormat: @"\"%@\"", __email];
  [ms appendString: @",expires:"];
  [ms appendFormat: @"%qi", __expires];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation Merchant_t

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithMerchantId: (int64_t) merchantId name: (NSString *) name email: (NSString *) email websiteUrl: (NSString *) websiteUrl logoUrl: (NSString *) logoUrl phone: (NSString *) phone address: (Address_t *) address created: (Timestamp) created updated: (Timestamp) updated
{
  self = [super init];
  __merchantId = merchantId;
  __merchantId_isset = YES;
  __name = [name retain_stub];
  __name_isset = YES;
  __email = [email retain_stub];
  __email_isset = YES;
  __websiteUrl = [websiteUrl retain_stub];
  __websiteUrl_isset = YES;
  __logoUrl = [logoUrl retain_stub];
  __logoUrl_isset = YES;
  __phone = [phone retain_stub];
  __phone_isset = YES;
  __address = [address retain_stub];
  __address_isset = YES;
  __created = created;
  __created_isset = YES;
  __updated = updated;
  __updated_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"merchantId"])
  {
    __merchantId = [decoder decodeInt64ForKey: @"merchantId"];
    __merchantId_isset = YES;
  }
  if ([decoder containsValueForKey: @"name"])
  {
    __name = [[decoder decodeObjectForKey: @"name"] retain_stub];
    __name_isset = YES;
  }
  if ([decoder containsValueForKey: @"email"])
  {
    __email = [[decoder decodeObjectForKey: @"email"] retain_stub];
    __email_isset = YES;
  }
  if ([decoder containsValueForKey: @"websiteUrl"])
  {
    __websiteUrl = [[decoder decodeObjectForKey: @"websiteUrl"] retain_stub];
    __websiteUrl_isset = YES;
  }
  if ([decoder containsValueForKey: @"logoUrl"])
  {
    __logoUrl = [[decoder decodeObjectForKey: @"logoUrl"] retain_stub];
    __logoUrl_isset = YES;
  }
  if ([decoder containsValueForKey: @"phone"])
  {
    __phone = [[decoder decodeObjectForKey: @"phone"] retain_stub];
    __phone_isset = YES;
  }
  if ([decoder containsValueForKey: @"address"])
  {
    __address = [[decoder decodeObjectForKey: @"address"] retain_stub];
    __address_isset = YES;
  }
  if ([decoder containsValueForKey: @"created"])
  {
    __created = [decoder decodeInt64ForKey: @"created"];
    __created_isset = YES;
  }
  if ([decoder containsValueForKey: @"updated"])
  {
    __updated = [decoder decodeInt64ForKey: @"updated"];
    __updated_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__merchantId_isset)
  {
    [encoder encodeInt64: __merchantId forKey: @"merchantId"];
  }
  if (__name_isset)
  {
    [encoder encodeObject: __name forKey: @"name"];
  }
  if (__email_isset)
  {
    [encoder encodeObject: __email forKey: @"email"];
  }
  if (__websiteUrl_isset)
  {
    [encoder encodeObject: __websiteUrl forKey: @"websiteUrl"];
  }
  if (__logoUrl_isset)
  {
    [encoder encodeObject: __logoUrl forKey: @"logoUrl"];
  }
  if (__phone_isset)
  {
    [encoder encodeObject: __phone forKey: @"phone"];
  }
  if (__address_isset)
  {
    [encoder encodeObject: __address forKey: @"address"];
  }
  if (__created_isset)
  {
    [encoder encodeInt64: __created forKey: @"created"];
  }
  if (__updated_isset)
  {
    [encoder encodeInt64: __updated forKey: @"updated"];
  }
}

- (void) dealloc
{
  [__name release_stub];
  [__email release_stub];
  [__websiteUrl release_stub];
  [__logoUrl release_stub];
  [__phone release_stub];
  [__address release_stub];
  [super dealloc_stub];
}

- (int64_t) merchantId {
  return __merchantId;
}

- (void) setMerchantId: (int64_t) merchantId {
  __merchantId = merchantId;
  __merchantId_isset = YES;
}

- (BOOL) merchantIdIsSet {
  return __merchantId_isset;
}

- (void) unsetMerchantId {
  __merchantId_isset = NO;
}

- (NSString *) name {
  return [[__name retain_stub] autorelease_stub];
}

- (void) setName: (NSString *) name {
  [name retain_stub];
  [__name release_stub];
  __name = name;
  __name_isset = YES;
}

- (BOOL) nameIsSet {
  return __name_isset;
}

- (void) unsetName {
  [__name release_stub];
  __name = nil;
  __name_isset = NO;
}

- (NSString *) email {
  return [[__email retain_stub] autorelease_stub];
}

- (void) setEmail: (NSString *) email {
  [email retain_stub];
  [__email release_stub];
  __email = email;
  __email_isset = YES;
}

- (BOOL) emailIsSet {
  return __email_isset;
}

- (void) unsetEmail {
  [__email release_stub];
  __email = nil;
  __email_isset = NO;
}

- (NSString *) websiteUrl {
  return [[__websiteUrl retain_stub] autorelease_stub];
}

- (void) setWebsiteUrl: (NSString *) websiteUrl {
  [websiteUrl retain_stub];
  [__websiteUrl release_stub];
  __websiteUrl = websiteUrl;
  __websiteUrl_isset = YES;
}

- (BOOL) websiteUrlIsSet {
  return __websiteUrl_isset;
}

- (void) unsetWebsiteUrl {
  [__websiteUrl release_stub];
  __websiteUrl = nil;
  __websiteUrl_isset = NO;
}

- (NSString *) logoUrl {
  return [[__logoUrl retain_stub] autorelease_stub];
}

- (void) setLogoUrl: (NSString *) logoUrl {
  [logoUrl retain_stub];
  [__logoUrl release_stub];
  __logoUrl = logoUrl;
  __logoUrl_isset = YES;
}

- (BOOL) logoUrlIsSet {
  return __logoUrl_isset;
}

- (void) unsetLogoUrl {
  [__logoUrl release_stub];
  __logoUrl = nil;
  __logoUrl_isset = NO;
}

- (NSString *) phone {
  return [[__phone retain_stub] autorelease_stub];
}

- (void) setPhone: (NSString *) phone {
  [phone retain_stub];
  [__phone release_stub];
  __phone = phone;
  __phone_isset = YES;
}

- (BOOL) phoneIsSet {
  return __phone_isset;
}

- (void) unsetPhone {
  [__phone release_stub];
  __phone = nil;
  __phone_isset = NO;
}

- (Address_t *) address {
  return [[__address retain_stub] autorelease_stub];
}

- (void) setAddress: (Address_t *) address {
  [address retain_stub];
  [__address release_stub];
  __address = address;
  __address_isset = YES;
}

- (BOOL) addressIsSet {
  return __address_isset;
}

- (void) unsetAddress {
  [__address release_stub];
  __address = nil;
  __address_isset = NO;
}

- (int64_t) created {
  return __created;
}

- (void) setCreated: (int64_t) created {
  __created = created;
  __created_isset = YES;
}

- (BOOL) createdIsSet {
  return __created_isset;
}

- (void) unsetCreated {
  __created_isset = NO;
}

- (int64_t) updated {
  return __updated;
}

- (void) setUpdated: (int64_t) updated {
  __updated = updated;
  __updated_isset = YES;
}

- (BOOL) updatedIsSet {
  return __updated_isset;
}

- (void) unsetUpdated {
  __updated_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setMerchantId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setEmail: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setWebsiteUrl: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 5:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setLogoUrl: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 6:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setPhone: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 7:
        if (fieldType == TType_STRUCT) {
          Address_t *fieldValue = [[Address_t alloc] init];
          [fieldValue read: inProtocol];
          [self setAddress: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 20:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setCreated: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 21:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setUpdated: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Merchant_t"];
  if (__merchantId_isset) {
    [outProtocol writeFieldBeginWithName: @"merchantId" type: TType_I64 fieldID: 1];
    [outProtocol writeI64: __merchantId];
    [outProtocol writeFieldEnd];
  }
  if (__name_isset) {
    if (__name != nil) {
      [outProtocol writeFieldBeginWithName: @"name" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __name];
      [outProtocol writeFieldEnd];
    }
  }
  if (__email_isset) {
    if (__email != nil) {
      [outProtocol writeFieldBeginWithName: @"email" type: TType_STRING fieldID: 3];
      [outProtocol writeString: __email];
      [outProtocol writeFieldEnd];
    }
  }
  if (__websiteUrl_isset) {
    if (__websiteUrl != nil) {
      [outProtocol writeFieldBeginWithName: @"websiteUrl" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __websiteUrl];
      [outProtocol writeFieldEnd];
    }
  }
  if (__logoUrl_isset) {
    if (__logoUrl != nil) {
      [outProtocol writeFieldBeginWithName: @"logoUrl" type: TType_STRING fieldID: 5];
      [outProtocol writeString: __logoUrl];
      [outProtocol writeFieldEnd];
    }
  }
  if (__phone_isset) {
    if (__phone != nil) {
      [outProtocol writeFieldBeginWithName: @"phone" type: TType_STRING fieldID: 6];
      [outProtocol writeString: __phone];
      [outProtocol writeFieldEnd];
    }
  }
  if (__address_isset) {
    if (__address != nil) {
      [outProtocol writeFieldBeginWithName: @"address" type: TType_STRUCT fieldID: 7];
      [__address write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  if (__created_isset) {
    [outProtocol writeFieldBeginWithName: @"created" type: TType_I64 fieldID: 20];
    [outProtocol writeI64: __created];
    [outProtocol writeFieldEnd];
  }
  if (__updated_isset) {
    [outProtocol writeFieldBeginWithName: @"updated" type: TType_I64 fieldID: 21];
    [outProtocol writeI64: __updated];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Merchant_t("];
  [ms appendString: @"merchantId:"];
  [ms appendFormat: @"%qi", __merchantId];
  [ms appendString: @",name:"];
  [ms appendFormat: @"\"%@\"", __name];
  [ms appendString: @",email:"];
  [ms appendFormat: @"\"%@\"", __email];
  [ms appendString: @",websiteUrl:"];
  [ms appendFormat: @"\"%@\"", __websiteUrl];
  [ms appendString: @",logoUrl:"];
  [ms appendFormat: @"\"%@\"", __logoUrl];
  [ms appendString: @",phone:"];
  [ms appendFormat: @"\"%@\"", __phone];
  [ms appendString: @",address:"];
  [ms appendFormat: @"%@", __address];
  [ms appendString: @",created:"];
  [ms appendFormat: @"%qi", __created];
  [ms appendString: @",updated:"];
  [ms appendFormat: @"%qi", __updated];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation Deal_t

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithDealId: (int64_t) dealId merchant: (Merchant_t *) merchant title: (NSString *) title summary: (NSString *) summary details: (NSString *) details code: (NSString *) code imageUrl: (NSString *) imageUrl expires: (Timestamp) expires created: (Timestamp) created updated: (Timestamp) updated
{
  self = [super init];
  __dealId = dealId;
  __dealId_isset = YES;
  __merchant = [merchant retain_stub];
  __merchant_isset = YES;
  __title = [title retain_stub];
  __title_isset = YES;
  __summary = [summary retain_stub];
  __summary_isset = YES;
  __details = [details retain_stub];
  __details_isset = YES;
  __code = [code retain_stub];
  __code_isset = YES;
  __imageUrl = [imageUrl retain_stub];
  __imageUrl_isset = YES;
  __expires = expires;
  __expires_isset = YES;
  __created = created;
  __created_isset = YES;
  __updated = updated;
  __updated_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"dealId"])
  {
    __dealId = [decoder decodeInt64ForKey: @"dealId"];
    __dealId_isset = YES;
  }
  if ([decoder containsValueForKey: @"merchant"])
  {
    __merchant = [[decoder decodeObjectForKey: @"merchant"] retain_stub];
    __merchant_isset = YES;
  }
  if ([decoder containsValueForKey: @"title"])
  {
    __title = [[decoder decodeObjectForKey: @"title"] retain_stub];
    __title_isset = YES;
  }
  if ([decoder containsValueForKey: @"summary"])
  {
    __summary = [[decoder decodeObjectForKey: @"summary"] retain_stub];
    __summary_isset = YES;
  }
  if ([decoder containsValueForKey: @"details"])
  {
    __details = [[decoder decodeObjectForKey: @"details"] retain_stub];
    __details_isset = YES;
  }
  if ([decoder containsValueForKey: @"code"])
  {
    __code = [[decoder decodeObjectForKey: @"code"] retain_stub];
    __code_isset = YES;
  }
  if ([decoder containsValueForKey: @"imageUrl"])
  {
    __imageUrl = [[decoder decodeObjectForKey: @"imageUrl"] retain_stub];
    __imageUrl_isset = YES;
  }
  if ([decoder containsValueForKey: @"expires"])
  {
    __expires = [decoder decodeInt64ForKey: @"expires"];
    __expires_isset = YES;
  }
  if ([decoder containsValueForKey: @"created"])
  {
    __created = [decoder decodeInt64ForKey: @"created"];
    __created_isset = YES;
  }
  if ([decoder containsValueForKey: @"updated"])
  {
    __updated = [decoder decodeInt64ForKey: @"updated"];
    __updated_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__dealId_isset)
  {
    [encoder encodeInt64: __dealId forKey: @"dealId"];
  }
  if (__merchant_isset)
  {
    [encoder encodeObject: __merchant forKey: @"merchant"];
  }
  if (__title_isset)
  {
    [encoder encodeObject: __title forKey: @"title"];
  }
  if (__summary_isset)
  {
    [encoder encodeObject: __summary forKey: @"summary"];
  }
  if (__details_isset)
  {
    [encoder encodeObject: __details forKey: @"details"];
  }
  if (__code_isset)
  {
    [encoder encodeObject: __code forKey: @"code"];
  }
  if (__imageUrl_isset)
  {
    [encoder encodeObject: __imageUrl forKey: @"imageUrl"];
  }
  if (__expires_isset)
  {
    [encoder encodeInt64: __expires forKey: @"expires"];
  }
  if (__created_isset)
  {
    [encoder encodeInt64: __created forKey: @"created"];
  }
  if (__updated_isset)
  {
    [encoder encodeInt64: __updated forKey: @"updated"];
  }
}

- (void) dealloc
{
  [__merchant release_stub];
  [__title release_stub];
  [__summary release_stub];
  [__details release_stub];
  [__code release_stub];
  [__imageUrl release_stub];
  [super dealloc_stub];
}

- (int64_t) dealId {
  return __dealId;
}

- (void) setDealId: (int64_t) dealId {
  __dealId = dealId;
  __dealId_isset = YES;
}

- (BOOL) dealIdIsSet {
  return __dealId_isset;
}

- (void) unsetDealId {
  __dealId_isset = NO;
}

- (Merchant_t *) merchant {
  return [[__merchant retain_stub] autorelease_stub];
}

- (void) setMerchant: (Merchant_t *) merchant {
  [merchant retain_stub];
  [__merchant release_stub];
  __merchant = merchant;
  __merchant_isset = YES;
}

- (BOOL) merchantIsSet {
  return __merchant_isset;
}

- (void) unsetMerchant {
  [__merchant release_stub];
  __merchant = nil;
  __merchant_isset = NO;
}

- (NSString *) title {
  return [[__title retain_stub] autorelease_stub];
}

- (void) setTitle: (NSString *) title {
  [title retain_stub];
  [__title release_stub];
  __title = title;
  __title_isset = YES;
}

- (BOOL) titleIsSet {
  return __title_isset;
}

- (void) unsetTitle {
  [__title release_stub];
  __title = nil;
  __title_isset = NO;
}

- (NSString *) summary {
  return [[__summary retain_stub] autorelease_stub];
}

- (void) setSummary: (NSString *) summary {
  [summary retain_stub];
  [__summary release_stub];
  __summary = summary;
  __summary_isset = YES;
}

- (BOOL) summaryIsSet {
  return __summary_isset;
}

- (void) unsetSummary {
  [__summary release_stub];
  __summary = nil;
  __summary_isset = NO;
}

- (NSString *) details {
  return [[__details retain_stub] autorelease_stub];
}

- (void) setDetails: (NSString *) details {
  [details retain_stub];
  [__details release_stub];
  __details = details;
  __details_isset = YES;
}

- (BOOL) detailsIsSet {
  return __details_isset;
}

- (void) unsetDetails {
  [__details release_stub];
  __details = nil;
  __details_isset = NO;
}

- (NSString *) code {
  return [[__code retain_stub] autorelease_stub];
}

- (void) setCode: (NSString *) code {
  [code retain_stub];
  [__code release_stub];
  __code = code;
  __code_isset = YES;
}

- (BOOL) codeIsSet {
  return __code_isset;
}

- (void) unsetCode {
  [__code release_stub];
  __code = nil;
  __code_isset = NO;
}

- (NSString *) imageUrl {
  return [[__imageUrl retain_stub] autorelease_stub];
}

- (void) setImageUrl: (NSString *) imageUrl {
  [imageUrl retain_stub];
  [__imageUrl release_stub];
  __imageUrl = imageUrl;
  __imageUrl_isset = YES;
}

- (BOOL) imageUrlIsSet {
  return __imageUrl_isset;
}

- (void) unsetImageUrl {
  [__imageUrl release_stub];
  __imageUrl = nil;
  __imageUrl_isset = NO;
}

- (int64_t) expires {
  return __expires;
}

- (void) setExpires: (int64_t) expires {
  __expires = expires;
  __expires_isset = YES;
}

- (BOOL) expiresIsSet {
  return __expires_isset;
}

- (void) unsetExpires {
  __expires_isset = NO;
}

- (int64_t) created {
  return __created;
}

- (void) setCreated: (int64_t) created {
  __created = created;
  __created_isset = YES;
}

- (BOOL) createdIsSet {
  return __created_isset;
}

- (void) unsetCreated {
  __created_isset = NO;
}

- (int64_t) updated {
  return __updated;
}

- (void) setUpdated: (int64_t) updated {
  __updated = updated;
  __updated_isset = YES;
}

- (BOOL) updatedIsSet {
  return __updated_isset;
}

- (void) unsetUpdated {
  __updated_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setDealId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRUCT) {
          Merchant_t *fieldValue = [[Merchant_t alloc] init];
          [fieldValue read: inProtocol];
          [self setMerchant: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setTitle: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setSummary: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 5:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setDetails: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 6:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setCode: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 7:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setImageUrl: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 8:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setExpires: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 20:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setCreated: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 21:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setUpdated: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Deal_t"];
  if (__dealId_isset) {
    [outProtocol writeFieldBeginWithName: @"dealId" type: TType_I64 fieldID: 1];
    [outProtocol writeI64: __dealId];
    [outProtocol writeFieldEnd];
  }
  if (__merchant_isset) {
    if (__merchant != nil) {
      [outProtocol writeFieldBeginWithName: @"merchant" type: TType_STRUCT fieldID: 2];
      [__merchant write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  if (__title_isset) {
    if (__title != nil) {
      [outProtocol writeFieldBeginWithName: @"title" type: TType_STRING fieldID: 3];
      [outProtocol writeString: __title];
      [outProtocol writeFieldEnd];
    }
  }
  if (__summary_isset) {
    if (__summary != nil) {
      [outProtocol writeFieldBeginWithName: @"summary" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __summary];
      [outProtocol writeFieldEnd];
    }
  }
  if (__details_isset) {
    if (__details != nil) {
      [outProtocol writeFieldBeginWithName: @"details" type: TType_STRING fieldID: 5];
      [outProtocol writeString: __details];
      [outProtocol writeFieldEnd];
    }
  }
  if (__code_isset) {
    if (__code != nil) {
      [outProtocol writeFieldBeginWithName: @"code" type: TType_STRING fieldID: 6];
      [outProtocol writeString: __code];
      [outProtocol writeFieldEnd];
    }
  }
  if (__imageUrl_isset) {
    if (__imageUrl != nil) {
      [outProtocol writeFieldBeginWithName: @"imageUrl" type: TType_STRING fieldID: 7];
      [outProtocol writeString: __imageUrl];
      [outProtocol writeFieldEnd];
    }
  }
  if (__expires_isset) {
    [outProtocol writeFieldBeginWithName: @"expires" type: TType_I64 fieldID: 8];
    [outProtocol writeI64: __expires];
    [outProtocol writeFieldEnd];
  }
  if (__created_isset) {
    [outProtocol writeFieldBeginWithName: @"created" type: TType_I64 fieldID: 20];
    [outProtocol writeI64: __created];
    [outProtocol writeFieldEnd];
  }
  if (__updated_isset) {
    [outProtocol writeFieldBeginWithName: @"updated" type: TType_I64 fieldID: 21];
    [outProtocol writeI64: __updated];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Deal_t("];
  [ms appendString: @"dealId:"];
  [ms appendFormat: @"%qi", __dealId];
  [ms appendString: @",merchant:"];
  [ms appendFormat: @"%@", __merchant];
  [ms appendString: @",title:"];
  [ms appendFormat: @"\"%@\"", __title];
  [ms appendString: @",summary:"];
  [ms appendFormat: @"\"%@\"", __summary];
  [ms appendString: @",details:"];
  [ms appendFormat: @"\"%@\"", __details];
  [ms appendString: @",code:"];
  [ms appendFormat: @"\"%@\"", __code];
  [ms appendString: @",imageUrl:"];
  [ms appendFormat: @"\"%@\"", __imageUrl];
  [ms appendString: @",expires:"];
  [ms appendFormat: @"%qi", __expires];
  [ms appendString: @",created:"];
  [ms appendFormat: @"%qi", __created];
  [ms appendString: @",updated:"];
  [ms appendFormat: @"%qi", __updated];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end


@implementation CoreConstants
+ (void) initialize {
}
@end

